wandb_version: 1

clip_coef:
  value: 0.23987359941888176
coef_align:
  value: 0.9875519492095024
coef_collision:
  value: 10
coef_gate:
  value: 15
coef_progress:
  value: 1.1881593261814265
coef_smooth:
  value: 0.024948689790335696
coef_spin:
  value: 0.006190189970037629
ent_coef:
  value: 0.0023437983332284325
gae_lambda:
  value: 0.95
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.0006287663706453999
num_steps:
  value: 16
vf_coef:
  value: 0.4000014602492809
