wandb_version: 1

clip_coef:
  value: 0.27353508408317007
coef_align:
  value: 0.5892107633522067
coef_collision:
  value: 10
coef_gate:
  value: 10
coef_progress:
  value: 1.9411160544920456
coef_smooth:
  value: 0.015376471286591038
coef_spin:
  value: 0.005644597032022933
ent_coef:
  value: 0.0029815105160433822
gae_lambda:
  value: 0.97
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.0002200124436583581
num_steps:
  value: 16
vf_coef:
  value: 0.4312631486475786
