wandb_version: 1

clip_coef:
  value: 0.28261336999696507
coef_align:
  value: 0.997122034997271
coef_collision:
  value: 5
coef_gate:
  value: 15
coef_progress:
  value: 1.5445785428984833
coef_smooth:
  value: 0.09676893986410444
coef_spin:
  value: 0.005187711019433264
ent_coef:
  value: 0.010731509544394332
gae_lambda:
  value: 0.95
gamma:
  value: 0.95
hidden_dim:
  value: 512
learning_rate:
  value: 0.0005569429710307412
num_steps:
  value: 16
vf_coef:
  value: 0.3445285632256962
