wandb_version: 1

clip_coef:
  value: 0.21782596204446855
coef_align:
  value: 0.9511523466347274
coef_collision:
  value: 10
coef_gate:
  value: 15
coef_progress:
  value: 0.6200863410896856
coef_smooth:
  value: 0.044755715388936225
coef_spin:
  value: 0.009408477573067797
ent_coef:
  value: 0.0017314520354603166
gae_lambda:
  value: 0.9
gamma:
  value: 0.95
hidden_dim:
  value: 512
learning_rate:
  value: 0.001546943918320852
num_steps:
  value: 16
vf_coef:
  value: 0.3929862574121518
