wandb_version: 1

clip_coef:
  value: 0.23712198681980048
coef_align:
  value: 0.9441404858548766
coef_collision:
  value: 5
coef_gate:
  value: 15
coef_progress:
  value: 1.316168827658488
coef_smooth:
  value: 0.1267553439878494
coef_spin:
  value: 0.0128079977664932
ent_coef:
  value: 0.02315534848813792
gae_lambda:
  value: 0.9
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.00013241784751353495
num_steps:
  value: 32
vf_coef:
  value: 0.3150976606678578
