wandb_version: 1

clip_coef:
  value: 0.10323195714426377
coef_align:
  value: 0.10273143029725045
coef_collision:
  value: 10
coef_gate:
  value: 10
coef_progress:
  value: 1.1414368358519416
coef_smooth:
  value: 0.01906277052844412
coef_spin:
  value: 0.05023680663357288
ent_coef:
  value: 0.006812933367164563
gae_lambda:
  value: 0.97
gamma:
  value: 0.97
hidden_dim:
  value: 128
learning_rate:
  value: 0.002168880890896103
num_steps:
  value: 32
vf_coef:
  value: 0.4251583492965038
