wandb_version: 1

clip_coef:
  value: 0.19502416369725728
coef_align:
  value: 0.8307038845140398
coef_collision:
  value: 10
coef_gate:
  value: 15
coef_progress:
  value: 1.6607298859188195
coef_smooth:
  value: 0.037263065331276275
coef_spin:
  value: 0.005118469945874891
ent_coef:
  value: 0.001738939210963926
gae_lambda:
  value: 0.9
gamma:
  value: 0.95
hidden_dim:
  value: 512
learning_rate:
  value: 0.0009524506241958314
num_steps:
  value: 16
vf_coef:
  value: 0.5339968194308796
