wandb_version: 1

clip_coef:
  value: 0.2875156332332428
coef_align:
  value: 0.9656647091425118
coef_collision:
  value: 5
coef_gate:
  value: 5
coef_progress:
  value: 0.7267239048603196
coef_smooth:
  value: 0.10130564110803308
coef_spin:
  value: 0.005158079463408315
ent_coef:
  value: 0.001270166334186415
gae_lambda:
  value: 0.97
gamma:
  value: 0.99
hidden_dim:
  value: 512
learning_rate:
  value: 0.0011295887244552284
num_steps:
  value: 16
vf_coef:
  value: 0.6917822203942539
