wandb_version: 1

clip_coef:
  value: 0.2967393543352792
coef_align:
  value: 0.7364660796912647
coef_collision:
  value: 5
coef_gate:
  value: 15
coef_progress:
  value: 0.8817956369731104
coef_smooth:
  value: 0.19310633266671745
coef_spin:
  value: 0.011959611626243948
ent_coef:
  value: 0.00256502826514292
gae_lambda:
  value: 0.97
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.00019856845694651463
num_steps:
  value: 16
vf_coef:
  value: 0.6871261048519635
