wandb_version: 1

clip_coef:
  value: 0.11876069477612183
coef_align:
  value: 0.1554620324616635
coef_collision:
  value: 5
coef_gate:
  value: 10
coef_progress:
  value: 1.106983935470439
coef_smooth:
  value: 0.03132288903267439
coef_spin:
  value: 0.02224448039866283
ent_coef:
  value: 0.007679160676638938
gae_lambda:
  value: 0.9
gamma:
  value: 0.95
hidden_dim:
  value: 256
learning_rate:
  value: 0.002391327924437255
num_steps:
  value: 32
vf_coef:
  value: 0.5514458822752725
