_wandb:
    value:
        cli_version: 0.22.3
        e:
            zgv3vb0sqdszkh6yd8r1oongrl1mrksj:
                args:
                    - --wandb_enabled=True
                    - --train=True
                    - --eval=0
                    - --clip_coef=0.2551260971105719
                    - --coef_align=0.29516933023802816
                    - --coef_collision=3
                    - --coef_gate=15
                    - --coef_progress=1.503924372670303
                    - --coef_smooth=0.43300273233078007
                    - --coef_spin=0.03090398050791006
                    - --ent_coef=0.011810759321292306
                    - --gae_lambda=0.95
                    - --gamma=0.95
                    - --hidden_dim=512
                    - --learning_rate=0.0005825244904038494
                    - --num_steps=64
                    - --vf_coef=0.6606521359785346
                codePath: lsy_drone_racing/rl_training/ppo_racing.py
                codePathLocal: ppo_racing.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "60152573952"
                        used: "24962686976"
                email: yuming6924@gmail.com
                executable: /data/repos/lsy_drone_racing/.pixi/envs/default/bin/python
                git:
                    commit: a36453b863befefeea3c9b053ced7d6e7ef8c401
                    remote: https://github.com/Yuming-Lee24/lsy_drone_racing.git
                gpu: NVIDIA GeForce RTX 2060 with Max-Q Design
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060 with Max-Q Design
                      uuid: GPU-b6197253-454c-8b9c-2c57-390d166e5b05
                host: ubuntu
                memory:
                    total: "16496250880"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /data/repos/lsy_drone_racing/lsy_drone_racing/rl_training/ppo_racing.py
                python: CPython 3.13.9
                root: /data/repos/lsy_drone_racing/lsy_drone_racing/rl_training
                startedAt: "2025-12-04T19:12:00.148492Z"
                writerId: zgv3vb0sqdszkh6yd8r1oongrl1mrksj
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 14
                - 16
                - 61
            "4": 3.13.9
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 65536
clip_coef:
    value: 0.2551260971105719
clip_vloss:
    value: true
coef_align:
    value: 0.29516933023802816
coef_collision:
    value: 3
coef_gate:
    value: 15
coef_progress:
    value: 1.503924372670303
coef_smooth:
    value: 0.43300273233078007
coef_spin:
    value: 0.03090398050791006
config_file:
    value: level3_stage1.toml
cuda:
    value: true
ent_coef:
    value: 0.011810759321292306
gae_lambda:
    value: 0.95
gamma:
    value: 0.95
hidden_dim:
    value: 512
jax_device:
    value: gpu
learning_rate:
    value: 0.0005825244904038494
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 8192
norm_adv:
    value: true
num_envs:
    value: 1024
num_iterations:
    value: 30
num_minibatches:
    value: 8
num_steps:
    value: 64
seed:
    value: 42
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 2000000
update_epochs:
    value: 10
vf_coef:
    value: 0.6606521359785346
wandb_entity:
    value: null
wandb_project_name:
    value: DroneRacing-PPO
