wandb_version: 1

clip_coef:
  value: 0.2361696480878696
coef_align:
  value: 0.6953664680276519
coef_collision:
  value: 5
coef_gate:
  value: 5
coef_progress:
  value: 0.9303455681937984
coef_smooth:
  value: 0.04704701500197862
coef_spin:
  value: 0.03743233295592461
ent_coef:
  value: 0.012478908326760518
gae_lambda:
  value: 0.9
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.00011034782983083247
num_steps:
  value: 16
vf_coef:
  value: 0.6447738966185451
