wandb_version: 1

clip_coef:
  value: 0.1603401793878137
coef_align:
  value: 0.15243222149510005
coef_collision:
  value: 10
coef_gate:
  value: 10
coef_progress:
  value: 1.2027763101916598
coef_smooth:
  value: 0.043168661733859505
coef_spin:
  value: 0.0171730194107227
ent_coef:
  value: 0.008966093369071532
gae_lambda:
  value: 0.97
gamma:
  value: 0.99
hidden_dim:
  value: 512
learning_rate:
  value: 0.0016531477977394348
num_steps:
  value: 64
vf_coef:
  value: 0.4852720645171631
