wandb_version: 1

clip_coef:
  value: 0.2551260971105719
coef_align:
  value: 0.29516933023802816
coef_collision:
  value: 3
coef_gate:
  value: 15
coef_progress:
  value: 1.503924372670303
coef_smooth:
  value: 0.43300273233078007
coef_spin:
  value: 0.03090398050791006
ent_coef:
  value: 0.011810759321292306
gae_lambda:
  value: 0.95
gamma:
  value: 0.95
hidden_dim:
  value: 512
learning_rate:
  value: 0.0005825244904038494
num_steps:
  value: 64
vf_coef:
  value: 0.6606521359785346
