wandb_version: 1

clip_coef:
  value: 0.23339613734569464
coef_align:
  value: 0.4648704131204232
coef_collision:
  value: 10
coef_gate:
  value: 5
coef_progress:
  value: 0.8930473130204145
coef_smooth:
  value: 0.032056001357522186
coef_spin:
  value: 0.01766544655466408
ent_coef:
  value: 0.04746613797197021
gae_lambda:
  value: 0.9
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.0008762320149063855
num_steps:
  value: 32
vf_coef:
  value: 0.6065967883816824
