wandb_version: 1

clip_coef:
  value: 0.2190419553189796
coef_align:
  value: 0.19465909553537744
coef_collision:
  value: 5
coef_gate:
  value: 5
coef_progress:
  value: 1.6964720791321424
coef_smooth:
  value: 0.03338244424183125
coef_spin:
  value: 0.09244212902913258
ent_coef:
  value: 0.0020614660043390617
gae_lambda:
  value: 0.9
gamma:
  value: 0.99
hidden_dim:
  value: 128
learning_rate:
  value: 0.0008779523398992542
num_steps:
  value: 64
vf_coef:
  value: 0.5866906531945897
