wandb_version: 1

clip_coef:
  value: 0.25874230741238713
coef_align:
  value: 0.204408983042219
coef_collision:
  value: 3
coef_gate:
  value: 5
coef_progress:
  value: 0.5111349056072724
coef_smooth:
  value: 0.02051025268389979
coef_spin:
  value: 0.008218506737534442
ent_coef:
  value: 0.007104830287373052
gae_lambda:
  value: 0.95
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.0002939634571618784
num_steps:
  value: 16
vf_coef:
  value: 0.5919625188676114
