wandb_version: 1

clip_coef:
  value: 0.18956106892987912
coef_align:
  value: 0.7841605338739105
coef_collision:
  value: 10
coef_gate:
  value: 5
coef_progress:
  value: 1.5711833884383526
coef_smooth:
  value: 0.4093855972233806
coef_spin:
  value: 0.02186242960094337
ent_coef:
  value: 0.010221545106520654
gae_lambda:
  value: 0.95
gamma:
  value: 0.95
hidden_dim:
  value: 128
learning_rate:
  value: 0.002080815242706313
num_steps:
  value: 32
vf_coef:
  value: 0.582500905858982
