wandb_version: 1

clip_coef:
  value: 0.24417591016479073
coef_align:
  value: 0.8237706515147977
coef_collision:
  value: 3
coef_gate:
  value: 10
coef_progress:
  value: 1.1544944346791943
coef_smooth:
  value: 0.23817368941721548
coef_spin:
  value: 0.007007762218507601
ent_coef:
  value: 0.0015886231657070093
gae_lambda:
  value: 0.95
gamma:
  value: 0.95
hidden_dim:
  value: 256
learning_rate:
  value: 0.0015118800617853366
num_steps:
  value: 32
vf_coef:
  value: 0.5345673598966946
