wandb_version: 1

clip_coef:
  value: 0.18499151455879048
coef_align:
  value: 0.4591777166290897
coef_collision:
  value: 10
coef_gate:
  value: 15
coef_progress:
  value: 1.2905785008774664
coef_smooth:
  value: 0.20127496390438945
coef_spin:
  value: 0.02982127472230519
ent_coef:
  value: 0.011291117964558213
gae_lambda:
  value: 0.9
gamma:
  value: 0.97
hidden_dim:
  value: 256
learning_rate:
  value: 0.00014933512527058737
num_steps:
  value: 32
vf_coef:
  value: 0.5466520657386846
