wandb_version: 1

clip_coef:
  value: 0.14768665570131834
coef_align:
  value: 0.3860144187825448
coef_collision:
  value: 5
coef_gate:
  value: 15
coef_progress:
  value: 0.5739486482683789
coef_smooth:
  value: 0.13577378506467347
coef_spin:
  value: 0.02311087037499709
ent_coef:
  value: 0.020077388145490555
gae_lambda:
  value: 0.95
gamma:
  value: 0.97
hidden_dim:
  value: 256
learning_rate:
  value: 0.000889945456138077
num_steps:
  value: 16
vf_coef:
  value: 0.498483443927209
