wandb_version: 1

clip_coef:
  value: 0.2676050146641087
coef_align:
  value: 0.7452032307216689
coef_collision:
  value: 3
coef_gate:
  value: 10
coef_progress:
  value: 0.839233463191964
coef_smooth:
  value: 0.024487272348632867
coef_spin:
  value: 0.05716895008713056
ent_coef:
  value: 0.005689300483994705
gae_lambda:
  value: 0.97
gamma:
  value: 0.97
hidden_dim:
  value: 256
learning_rate:
  value: 0.0011256666274712397
num_steps:
  value: 16
vf_coef:
  value: 0.5246456489509932
