wandb_version: 1

clip_coef:
  value: 0.2586432746986121
coef_align:
  value: 0.6282677958031491
coef_collision:
  value: 10
coef_gate:
  value: 10
coef_progress:
  value: 0.5141183298428895
coef_smooth:
  value: 0.05682666187024888
coef_spin:
  value: 0.03800647768574608
ent_coef:
  value: 0.02048656589370476
gae_lambda:
  value: 0.9
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.00016026678858670632
num_steps:
  value: 16
vf_coef:
  value: 0.6917653736367362
