wandb_version: 1

clip_coef:
  value: 0.14582394605893895
coef_align:
  value: 0.4483602206580415
coef_collision:
  value: 3
coef_gate:
  value: 10
coef_progress:
  value: 1.2867154545552917
coef_smooth:
  value: 0.19802283246985555
coef_spin:
  value: 0.05923832336900054
ent_coef:
  value: 0.0023573001628263627
gae_lambda:
  value: 0.95
gamma:
  value: 0.95
hidden_dim:
  value: 512
learning_rate:
  value: 0.0007060873650494302
num_steps:
  value: 16
vf_coef:
  value: 0.42731469411907214
