wandb_version: 1

clip_coef:
  value: 0.28185837719813345
coef_align:
  value: 0.40640804212923054
coef_collision:
  value: 5
coef_gate:
  value: 10
coef_progress:
  value: 1.0444487009428065
coef_smooth:
  value: 0.013389882472838193
coef_spin:
  value: 0.07613664682751466
ent_coef:
  value: 0.015061996329351733
gae_lambda:
  value: 0.9
gamma:
  value: 0.95
hidden_dim:
  value: 128
learning_rate:
  value: 0.0017574399440547538
num_steps:
  value: 16
vf_coef:
  value: 0.32660823846220916
