wandb_version: 1

clip_coef:
  value: 0.1046155583536697
coef_align:
  value: 0.1881588853946057
coef_collision:
  value: 5
coef_gate:
  value: 15
coef_progress:
  value: 1.5785564557204834
coef_smooth:
  value: 0.03551994275042961
coef_spin:
  value: 0.04223311592035482
ent_coef:
  value: 0.0012937005235478475
gae_lambda:
  value: 0.95
gamma:
  value: 0.97
hidden_dim:
  value: 512
learning_rate:
  value: 0.000524873975569799
num_steps:
  value: 64
vf_coef:
  value: 0.4765296656563303
