wandb_version: 1

clip_coef:
  value: 0.23001304610329412
coef_align:
  value: 0.4284918204661457
coef_collision:
  value: 5
coef_gate:
  value: 10
coef_progress:
  value: 1.383580623187802
coef_smooth:
  value: 0.0685297585125964
coef_spin:
  value: 0.04077023624477769
ent_coef:
  value: 0.001404033157370551
gae_lambda:
  value: 0.97
gamma:
  value: 0.99
hidden_dim:
  value: 128
learning_rate:
  value: 0.0005264510324440259
num_steps:
  value: 16
vf_coef:
  value: 0.6944089671666336
