_wandb:
    value:
        cli_version: 0.22.3
        e:
            hqrtw6577b2oa5fu6gk40fnje4ckjk8o:
                args:
                    - --wandb_enabled=True
                    - --train=True
                    - --eval=0
                    - --clip_coef=0.10520791309351314
                    - --ent_coef=0.003380637483662815
                    - --gae_lambda=0.9
                    - --gamma=0.95
                    - --hidden_dim=512
                    - --learning_rate=0.002303345861277985
                    - --num_steps=16
                    - --vf_coef=0.6426868016302685
                codePath: lsy_drone_racing/rl_training/ppo_racing.py
                codePathLocal: ppo_racing.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "60152573952"
                        used: "25022210048"
                email: yuming6924@gmail.com
                executable: /data/repos/lsy_drone_racing/.pixi/envs/default/bin/python
                git:
                    commit: 03880b35457cd54b777d78a3d328a83879d1023d
                    remote: https://github.com/Yuming-Lee24/lsy_drone_racing.git
                gpu: NVIDIA GeForce RTX 2060 with Max-Q Design
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060 with Max-Q Design
                      uuid: GPU-b6197253-454c-8b9c-2c57-390d166e5b05
                host: ubuntu
                memory:
                    total: "16496238592"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /data/repos/lsy_drone_racing/lsy_drone_racing/rl_training/ppo_racing.py
                python: CPython 3.13.9
                root: /data/repos/lsy_drone_racing/lsy_drone_racing/rl_training
                startedAt: "2025-12-06T05:01:31.842222Z"
                writerId: hqrtw6577b2oa5fu6gk40fnje4ckjk8o
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 14
                - 16
                - 61
            "4": 3.13.9
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 16384
clip_coef:
    value: 0.10520791309351314
clip_vloss:
    value: true
coef_align:
    value: 0.5
coef_angle:
    value: 0.06
coef_collision:
    value: 5
coef_gate:
    value: 10
coef_progress:
    value: 1
coef_smooth:
    value: 0.1
coef_spin:
    value: 0.02
config_file:
    value: level0_no_obst.toml
cuda:
    value: true
ent_coef:
    value: 0.003380637483662815
gae_lambda:
    value: 0.9
gamma:
    value: 0.95
hidden_dim:
    value: 512
jax_device:
    value: gpu
learning_rate:
    value: 0.002303345861277985
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 2048
norm_adv:
    value: true
num_envs:
    value: 1024
num_iterations:
    value: 122
num_minibatches:
    value: 8
num_steps:
    value: 16
seed:
    value: 42
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 2000000
update_epochs:
    value: 10
vf_coef:
    value: 0.6426868016302685
wandb_entity:
    value: null
wandb_project_name:
    value: DroneRacing-PPO
