_wandb:
    value:
        cli_version: 0.22.3
        e:
            fgxy7m5cayksqur2cbxrs9c0ppsz31kq:
                args:
                    - --wandb_enabled=True
                    - --train=True
                    - --eval=0
                    - --clip_coef=0.14768665570131834
                    - --coef_align=0.3860144187825448
                    - --coef_collision=5
                    - --coef_gate=15
                    - --coef_progress=0.5739486482683789
                    - --coef_smooth=0.13577378506467347
                    - --coef_spin=0.02311087037499709
                    - --ent_coef=0.020077388145490555
                    - --gae_lambda=0.95
                    - --gamma=0.97
                    - --hidden_dim=256
                    - --learning_rate=0.000889945456138077
                    - --num_steps=16
                    - --vf_coef=0.498483443927209
                codePath: lsy_drone_racing/rl_training/ppo_racing.py
                codePathLocal: ppo_racing.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "60152573952"
                        used: "24962678784"
                email: yuming6924@gmail.com
                executable: /data/repos/lsy_drone_racing/.pixi/envs/default/bin/python
                git:
                    commit: a36453b863befefeea3c9b053ced7d6e7ef8c401
                    remote: https://github.com/Yuming-Lee24/lsy_drone_racing.git
                gpu: NVIDIA GeForce RTX 2060 with Max-Q Design
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1920
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 2060 with Max-Q Design
                      uuid: GPU-b6197253-454c-8b9c-2c57-390d166e5b05
                host: ubuntu
                memory:
                    total: "16496250880"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /data/repos/lsy_drone_racing/lsy_drone_racing/rl_training/ppo_racing.py
                python: CPython 3.13.9
                root: /data/repos/lsy_drone_racing/lsy_drone_racing/rl_training
                startedAt: "2025-12-04T19:08:16.012832Z"
                writerId: fgxy7m5cayksqur2cbxrs9c0ppsz31kq
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 14
                - 16
                - 61
            "4": 3.13.9
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 16384
clip_coef:
    value: 0.14768665570131834
clip_vloss:
    value: true
coef_align:
    value: 0.3860144187825448
coef_collision:
    value: 5
coef_gate:
    value: 15
coef_progress:
    value: 0.5739486482683789
coef_smooth:
    value: 0.13577378506467347
coef_spin:
    value: 0.02311087037499709
config_file:
    value: level3_stage1.toml
cuda:
    value: true
ent_coef:
    value: 0.020077388145490555
gae_lambda:
    value: 0.95
gamma:
    value: 0.97
hidden_dim:
    value: 256
jax_device:
    value: gpu
learning_rate:
    value: 0.000889945456138077
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 2048
norm_adv:
    value: true
num_envs:
    value: 1024
num_iterations:
    value: 122
num_minibatches:
    value: 8
num_steps:
    value: 16
seed:
    value: 42
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 2000000
update_epochs:
    value: 10
vf_coef:
    value: 0.498483443927209
wandb_entity:
    value: null
wandb_project_name:
    value: DroneRacing-PPO
